<a href="https://colab.research.google.com/github/ngost2002/MATH_AI/blob/main/basic_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


In this sheet we'll make sure you can use the standard tensor technique in PyTorch, and also that you can read and write files.


In [ ]:
import torch
import math


In [ ]:
# the following examples are from the notes, exluding the Numpy example
A = torch.tensor([[1., -1.], [1., -1.]])
# B = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
C = torch.empty(3, 4)
D = torch.zeros(2, 3, 4)
E = torch.ones(1, 1, 2, dtype=torch.int16)
torch.manual_seed(1729)
F = torch.rand(2, 3, dtype=torch.float64)

You can look at the variables by clicking on the `{x}` on the left-hand margin of this page. Double-click on one to see it in detail.

Next practice doing some standard operations.

In [ ]:
# Take the transpose of A.
A_transpose = torch.transpose(A,0,1)
print(A_tranpose)

# Squeeze the length=1 dimensions of E.
E_squeeze= torch.squeeze(E)
print(E_squeeze)

# Add up the columns of A
A_cadd= torch.sum(A, dim=0)
print(A_cadd)

# Multiply A by 3.0
A_mult= 3*A
print(A_mult)

# Find the element from the 1st row and 2nd column of A (careful!)
print(A[0,1])

# Use torch.arange() to construct a vector 1,...,5 and square all of its elements
y= torch.arange(1,6)
x= torch.square(y)
print(x)

# Use a comprehension to do the same (as in the previous case)
b = torch.tensor([i**2 for i in y])
print(b)



tensor([[ 1.,  1.],
        [-1., -1.]])
tensor([1, 1], dtype=torch.int16)
tensor([ 2., -2.])
tensor([[ 3., -3.],
        [ 3., -3.]])
tensor(-1.)
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])


Now we will input a tensor and save the result of a calculation. PyTorch does most stuff with tensors so we will use its stsandard file format, which has the suffix `.pt`.

There is a file called `Data/tensor.pt` in the GitHub repository. Grab that file and save it into your Google Drive.

Then we use Google Colab's packages to access that file. You'll have to do some autorisation along the way. I also created a `Data` folder on my drive to store such things. You code will have to vary if you put your data somewhere else.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
%cd /content/drive/MyDrive/Data
%ls

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Data
tensor.pt


Now you should be able to read from (your base) Google Drive folder.

In [ ]:
A = torch.load('/content/drive/My Drive/Data/tensor.pt')


You should also be able to save a file to that directory.

In [ ]:
torch.save(A, '/content/drive/My Drive/Data/tensor.pt')

And also save the file back to your computer.

In [ ]:
files.download('/content/drive/My Drive/Data/tensor.pt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

There are many other such commands, including commands to get files direct from a web server (which we use with the MNIST dataset).

In [ ]:
# now create your own tensor, and save it to a file
Test = torch.tensor([[3,4],[5,6]])
torch.save(Test, '/content/drive/My Drive/Data/my_test.pt')
files.download('/content/drive/My Drive/Data/my_test.pt')
# now read it back into a new variable
B=torch.load('/content/drive/My Drive/Data/my_test.pt')
print(B)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

tensor([[3, 4],
        [5, 6]])


In [ ]:
print(A)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999, 0.3971, 0.7544, 0.5695,
         0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980, 0.9371,
         0.6556],
        [0.3138, 0.1980, 0.4162, 0.2843, 0.3398, 0.5239, 0.7981, 0.7718, 0.0112,
         0.8100],
        [0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588, 0.9391, 0.4167, 0.7140,
         0.2676],
        [0.9906, 0.2885, 0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471, 0.3556,
         0.4452],
        [0.0193, 0.2616, 0.7713, 0.3785, 0.9980, 0.9008, 0.4766, 0.1663, 0.8045,
         0.6552],
        [0.1768, 0.8248, 0.8036, 0.9434, 0.2197, 0.4177, 0.4903, 0.5730, 0.1205,
         0.1452],
        [0.7720, 0.3828, 0.7442, 0.5285, 0.6642, 0.6099, 0.6818, 0.7479, 0.0369,
         0.7517],
        [0.1484, 0.1227, 0.5304, 0.4148, 0.7937, 0.2104, 0.0555, 0.8639, 0.4259,
         0.7812],
        [0.6607, 0.1251, 0.6004, 0.6201, 0.1652, 0.2628, 0.6705, 0.5896, 0.2873,
         0.3486]])
